# Set IP and port of other RPi.
IP = "punpun.xyz:8080"

# Set port to listen to when primary.
port = 8080

# Set interval in seconds at which to execute script.
interval = 4

# Set path to script to run.
script = "./script/aasgier.sh"
